### ISSUE TITLE
VSCodeでソースコードを編集する際にeslintの警告が表示される

### ISSUE THREAD

**Issue by knokmki612** [webdino/lyceum-pokemon#100]
例えばNuxtの自動インポートで呼び出している関数などについて未定義の関数としてリントに引っかかる

VSCodeでもインライン表示され学習ノイズとなるようなのでリントをパスするような形でセットアップできればよりよい

**Comment by dynamis** [comment]
Nuxt 3 側で用意してくれてるものを使う設定が出来ていない？

https://github.com/nuxt/eslint-plugin-nuxt

何か色々あるようだけど詳細未確認:
https://github.com/nuxt/eslint-plugin-nuxt/issues/173

**Comment by knokmki612** [comment]
そうですね、Nuxtのプリセットを使用するような設定になっていないことは確かなのでそのあたり調査とセットアップが必要です https://github.com/webdino/lyceum-pokemon/blob/main/.eslintrc.yaml#L3-L3

**Comment by knokmki612** [comment]
https://github.com/nuxt/eslint-config

こちらは開発が止まっており、v3対応は案内いただいたeslint-plugin-nuxtでおこなっている？

**Comment by knokmki612** [comment]
https://github.com/nuxt/eslint-config/releases/tag/%40nuxt%2Feslint-config%400.1.0 にて正式な nuxt 3 プリセット対応がおこなわれたので、こちらを導入します
