### ISSUE TITLE
App Runner での動作確認

### ISSUE THREAD

**Issue by knokmki612** [webdino/lyceum-pokemon#104]
本アプリを App Runner にデプロイし、デプロイ先の URL からアクセス、正常にできることを確認できたら完了

**Comment by knokmki612** [comment]
## 準備: ロールの作成

https://us-east-1.console.aws.amazon.com/iamv2/home#/roles より「ロールを作成」をクリック

![image](https://user-images.githubusercontent.com/9744580/223363983-7ba07dea-700a-4c86-a318-6b46838d5514.png)

カスタム信頼ポリシーを選択し、以下のカスタム信頼ポリシーを作成

参考: 講義資料 Day8 p.38 と https://zenn.dev/becominn/articles/3c06bc732f8775

```json
{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "Statement1",
			"Effect": "Allow",
			"Principal": {
			    "Service": "tasks.apprunner.amazonaws.com"
			},
			"Action": "sts:AssumeRole"
		}
	]
}
```

許可ポリシーから AmazonS3FullAccess を指定

![image](https://user-images.githubusercontent.com/9744580/223365216-349a5832-5321-4735-b51d-d399ca360c84.png)

ロール名を入力して作成

![image](https://user-images.githubusercontent.com/9744580/223365316-ab1c10da-4625-4c68-aa62-9c25b939f090.png)

## App Runner サービスの作成

https://us-east-1.console.aws.amazon.com/apprunner/home#/services からサービスの作成をクリック

![image](https://user-images.githubusercontent.com/9744580/223365836-33b96d1c-3235-4618-af85-06c7f1f47658.png)

リポジトリタイプは「ソースコードリポジトリ」を指定、必要に応じてAWS Connector for GitHubアプリをインストールし、webdino/lyceum-pokemonをフォークしたリポジトリを指定

![image](https://user-images.githubusercontent.com/9744580/223365958-b0c32e9b-c15c-489d-8d67-6a023721ac60.png)

下記の通り設定

![image](https://user-images.githubusercontent.com/9744580/223366357-46673db3-f7d3-482c-b507-7af4303d2e64.png)

環境変数を設定（NUXT_PUBLIC_BACKEND_ORIGINの指定が必要だが初回は諦める。デプロイ後デフォルトドメインが分かるのでデプロイ成功後追加）

![image](https://user-images.githubusercontent.com/9744580/223367409-505b0e11-2e4b-4ac7-a80d-c3afa9277b17.png)

準備で作成したIAMロールをインスタンスロールとして指定

![image](https://user-images.githubusercontent.com/9744580/223367112-faa5a38c-b26f-476a-853f-af3ef558be3a.png)

**Comment by dynamis** [comment]
> 環境変数を設定

スクショでは HOST, PORT の指定もしている / README でも指定が必要とあるが、これらは省略しても問題無さそうです。

> NUXT_PUBLIC_BACKEND_ORIGINの指定が必要だが初回は諦める。デプロイ後デフォルトドメインが分かるのでデプロイ成功後追加

ここだけ少し面倒だが仕方ない感じですね。そしてそこの指定の末尾 / を入れると Vue Router の制限に引っかかって次のエラーで起動しない / デプロイがロールバックされる 事に要注意

```
[Vue Router warn]: Location "[object Object]" resolved to "//api/trainers". A resolved location cannot start with multiple slashes.
[Vue Router warn]: Location "//api/trainers" resolved to "//api/trainers". A resolved location cannot start with multiple slashes.
[nuxt] error caught during app initialization H3Error: Page not found: //api/trainers
```

**Comment by knokmki612** [comment]
> NUXT_PUBLIC_BACKEND_ORIGINの指定が必要だが初回は諦める。デプロイ後デフォルトドメインが分かるのでデプロイ成功後追加

#134 の変更により、NUXT_PUBLIC_BACKEND_ORIGINが指定不要になりました。あわせて初回デプロイ成功後判明するオリジンも不要、つまり初回デプロイに成功すれば2回目デプロイの作業は不要になりました。

**Comment by dynamis** [comment]
最新の環境での構築試験 (事前実施済みのロール設定部分は省略、デフォルト設定から変えている部分のみスクショ):

![image](https://github.com/webdino/lyceum-pokemon/assets/188166/592a8b3d-af1d-42e6-9791-c7f5c3dbf492)
![image](https://github.com/webdino/lyceum-pokemon/assets/188166/f10b525d-b001-4db5-8578-7e9c31981975)
![image](https://github.com/webdino/lyceum-pokemon/assets/188166/ddb61de6-61e2-4ba5-8550-609b694d74b7)

環境変数設定がどう考えても必須である NUXT_BUCKET_NAME 以外は完全デフォルトでサクッと動作するようになってとても楽になりました。

**Comment by knokmki612** [comment]
https://github.com/webdino/lyceum-pokemon/issues/104#issuecomment-1907159549 のスクリーンショットを #141 にて使用させていただきました :pray:

本issueにあたるタスクは今後必要なタイミングで起票するつもりで、 #141 のマージを持ってクローズしようと思います。
