### ISSUE TITLE
ひととおりのローカル環境での動作確認

### ISSUE THREAD

**Issue by knokmki612** [webdino/lyceum-pokemon#110]
@knokmki612 の手元でも動作確認するがそれ以外でも動かしてもらう（もちろん @dynamis にもしていただけるだろうがそれとは別で @Hidetaro7 に依頼する）

**Comment by knokmki612** [comment]
@Hidetaro7 現在ローカルでの動作確認可能な状態かと思います

**Comment by Hidetaro7** [comment]
一通り基本的な動作を確認して、問題ないと思いました。
