### ISSUE TITLE
Heroku へのデプロイのドキュメンテーションの取り扱い

### ISSUE THREAD

**Issue by knokmki612** [webdino/lyceum-pokemon#117]
研修ではもう使用しないかと思うので廃止もありうるかと思った

https://github.com/webdino/lyceum-pokemon/blob/main/README.md#heroku-%E3%81%B8%E3%81%AE%E3%83%87%E3%83%97%E3%83%AD%E3%82%A4

**Comment by knokmki612** [comment]
メンテナンス性という観点ではもちろん廃止した方が動作確認すべき環境が減りうれしいかと思う

**Comment by kou029w** [comment]
廃止でよいかと思います
