### ISSUE TITLE
商標、著作物の取り扱い

### ISSUE THREAD

**Issue by knokmki612** [webdino/lyceum-pokemon#17]
> ポケットモンスター＼ポケモン、ポケモントレーナー＼ポケトレ、モンスターボールは任天堂株式会社の商標です

のような表記が必要かと思ったが法的根拠はなさそう

参考: https://shousei.jp/topics/%E4%BB%96%E4%BA%BA%E3%81%AE%E5%95%86%E6%A8%99%E3%81%AE%E5%BC%95%E7%94%A8/

またpokeapiを使っていることについてなにか断りがあったほうがいいのか気になった

参考: https://note.com/hatanowf/n/n7f6ef8b0ea7c

### 背景

見た目を用意するにあたり、モンスターボールが https://zukan.pokemon.co.jp/ などでは使われているのでこのアプリでもつかうと「それっぽさ」が出るかと思った

どの程度似せていいのか、似せるときになにか配慮する点があるのか気になった

ちなみにモンスターボールの登録意匠は https://www.j-platpat.inpit.go.jp/ で検索してみたが見つからなかった

**Comment by dynamis** [comment]
正式なサイトを作って外部に公開するというものではなく、単にサンプルコードとして演習に使っているだけのものなので、リリースするアプリや製品において必要とされる要件を満たした形で作りましょうという前提ではないです。

何か書くとしてもリポジトリ全体の README だけでサンプルコード中に書く必要はないです。

**Comment by knokmki612** [comment]
https://www.bunka.go.jp/seisaku/chosakuken/seidokaisetsu/gaiyo/chosakubutsu_jiyu.html なども参照してみましたがいまいち現状よりよい有効な記載方法が思いつかないので、一旦取り下げたいと思います
