### ISSUE TITLE
serverMiddlewareに関するドキュメントのリンクの修正

### ISSUE THREAD

**Issue by Hidetaro7** [webdino/lyceum-pokemon#23]
https://github.com/webdino/lyceum-pokemon/blob/a40aaff1441df78adc1b67bebaef95aa3fd323e9/nuxt.config.ts#L3

初見で見る限りここのリンクに置き換えたほうが学習しやすいと思った...けど、config全体の説明なのでこれでいいのかもしれない。

https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
↓
https://v3.nuxtjs.org/docs/directory-structure/nuxt.config#servermiddleware

**Comment by knokmki612** [comment]
現状挿入されているコメントは `nuxi create` で提供されているボイラープレートに含まれているものですね

**Comment by Hidetaro7** [comment]
ワタシ的に調べてみたときに感じたことで、教材なので教えるときにスムーズかと感じただけです。
特にIssueにするほどではなかったかもしれません。不要であればクローズしてもらって構いません。

**Comment by knokmki612** [comment]
教えるというのがどのような場面を想定されているのかが分からなかったです。

ひとまずコメントとしてserverMiddlewareに関するドキュメンテーションが追加される事自体は異存ないです。
