### ISSUE TITLE
見た目とふるまいの調整

### ISSUE THREAD

**Issue by knokmki612** [webdino/lyceum-pokemon#26]
現状ブラウザのデフォルトスタイルのみの見た目になっている

私案

- [x] 初代ポケモン風の太めで角丸の枠線の使用
- [x] 適切な余白の調整
- [x] 取り消せない操作（削除系）へのダイアログの提供
- [x] ボタンのテキストボタンの見た目の提供
- [ ] 待機状態（データの取得中, etc.）の見た目の提供

**Comment by Hidetaro7** [comment]
3/3以降にひできがここを担当する

**Comment by knokmki612** [comment]
> ボタンのテキストボタンの見た目の提供
> 待機状態（データの取得中, etc.）の見た目の提供

今日取り組んでみたところ、いずれも必須というほどではないかなという状況です

**Comment by Hidetaro7** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/281424/156509118-8b637852-ce20-48e7-9de6-7ae9e2d52966.png">
<img width="375" alt="image" src="https://user-images.githubusercontent.com/281424/156509179-30685d23-93fb-4a38-b3c0-2809c523f3dc.png">
ボタンの定義をどうするかについては悩みどころで、今は直接`button`要素と`.button`クラスに付与している  
あまりソースコードに見た目のコードを追加すると本講義の趣旨に対してノイズになりそうなので、これくらいでとどめておこうかと思う

**Comment by Hidetaro7** [comment]
[animation.css](https://animate.style/)を導入して、ポケモンボールなどをバウンスさせてみた

**Comment by Hidetaro7** [comment]
関連 https://github.com/webdino/lyceum-pokemon/pull/40

**Comment by knokmki612** [comment]
ボタンの見た目は導入した他の見た目との差別化や整合性を考慮すると、デフォルトスタイルのものでいいかと思っていました

ともかく明日整理する機会をください

**Comment by knokmki612** [comment]
> ボタンの見た目は導入した他の見た目との差別化や整合性を考慮すると、デフォルトスタイルのものでいいかと思っていました

私の環境で試してみましたが用意いただいたものでも利用上問題ないわけではなさそうと思いました

表示系と似たスタイルなので見分けがつきにくいかと思いましたが、ボタンのラベリング、配置などによってある程度ボタンと予測できそうかなと思いました

**Comment by Hidetaro7** [comment]
> ボタンの見た目は導入した他の見た目との差別化や整合性を考慮すると、デフォルトスタイルのものでいいかと思っていました

ポケモンという世界観の整合性という意味ではボタンがデフォルトスタイルだとちょっと違和感が感じられたのでこうしてみたのですが、おっしゃるとおり表示系もボタンも見た目が同じってところが若干気になったというのは同意です。
個人的なこだわりというより教材としてどの観点で決定するかが大事だと思うので相談したいところです。

**Comment by knokmki612** [comment]
> 用意いただいたものでも利用上問題ないわけではなさそうと思いました

aタグ、NuxtLinkのリンクとbuttonタグのボタンはそれぞれUI部品としてもった作用（一方は画面遷移、一方は画面上のアクション）がことなるので、同じ見た目にするのは抵抗を感じました

**Comment by knokmki612** [comment]
> ポケモンという世界観の整合性

この点に関しては、最近の作品はタッチペン、タッチパネルのゲーム機でボタン的な見た目が充実していると思うのですが、初代のポケモンのゲーム画面をみると、ゲーム機のボタンが画面上のボタンに相当する役割を担っているので、ボタン的な見た目がそもそも存在しないな、ということに気づきました

**Comment by knokmki612** [comment]
> 同じ見た目にするのは抵抗を感じました

今回はウェブページというよりアプリとして見た目を考えているので、同じ見た目であることは許容する方針にすることになった
