### ISSUE TITLE
アプリの実装過程、実装内容について説明する準備をする

### ISSUE THREAD

**Issue by knokmki612** [webdino/lyceum-pokemon#53]
所要時間: 30分程度
どんなふうにつくったか、なにが大変だったか
実装の質問の受け答え

**Comment by knokmki612** [comment]
参考にしたものなどコメントしていき、ヒントになりそうなものについては #54 でも活用する

**Comment by knokmki612** [comment]
基本的に https://github.com/webdino/lyceum-pokemon/issues?q=sort%3Acreated-asc を順番に見ていけば、ほぼほぼ実態に沿った今回の実装過程が分かる

**Comment by knokmki612** [comment]
- #2
    - あまり時間をかけなかった（伏線）
- #3
- #4
    - 事前に検討した API エンドポイントの書き出し
    - 名前付け、必要なパラメーターの兼ね合いで、結局実装しながら流動的に仕様が変わった
- #10
    - 今回の API エンドポイントの実装においてかなり実際的なコードの断片を得た
    - 参考にしたドキュメント
        - [Amazon S3 バケットの作成と使用 - AWS SDK for JavaScript](https://docs.aws.amazon.com/ja_jp/sdk-for-javascript/v3/developer-guide/s3-example-creating-buckets.html) シナリオとともに今回必要な S3 関連の実装の 8 割くらいはここに分かりやすく記載されていた
        - [S3 Client - AWS SDK for JavaScript v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-s3/index.html) 必要なコマンドがどれかは勘で探していた
- #11
    - 本アプリで取り扱うデータ構造を整理する必要があった
    - API エンドポイントの実装にあたって、タスクを分解することで手が止まらないようにしたかった
- #13
    - https://github.com/webdino/lyceum-pokemon/pull/13/commits/f772716c87fed32d455696826b902281192e1846 でコードの見通しがよくなった
    - https://github.com/webdino/lyceum-pokemon/pull/13/commits/20ae2b19e045cee2dc5347def9e79c23e3f70aed ポケモンの採番処理はちょくちょく触っている（後述）
    - Express は使ったことがあったが https://github.com/webdino/lyceum-pokemon/pull/13/commits/754b595bbc1d9087c7d6484e17541c2758840e59 を忘れていた
- #15 
    - 画面構成の検討は逆に実装から着手したほうがかえって手が止まらなかったかもしれない
- #20 
    - ハマりポイントだった
- #22
    - この時点で（完成度はともかく）ほぼほぼサーバー側とクライアント側ができた
    - https://github.com/webdino/lyceum-pokemon/pull/22/commits/de2ad73a968f99bbc7cdab574122a53963fb8358 伏線
- #26
    - 見た目の方針決めをおこなった
- #28 
    - 依頼されておらず研修でも使うことがなかったが、アプリのデバッグ作業にもなった
- #29
    - デバッグの成果
- #30
    - デバッグの成果
- #32
    - アプリのデバッグ作業にもなった
- #34
    - デバッグの成果
- #35
    - サーバー側のバリデーションをもう少しちゃんとしようとした
- #37
    - 見た目のための作業（楽しい人は楽しいし楽しくない人は楽しくないらしい）
- #38
    - 見た目のための作業（楽しい人は楽しいし楽しくない人は楽しくないらしい）
    - https://github.com/webdino/lyceum-pokemon/pull/38/commits/536b7e12b74686f4183ca4c7a4a65e96c2ddfd65 は https://github.com/webdino/lyceum-pokemon/pull/22/commits/de2ad73a968f99bbc7cdab574122a53963fb8358 の変更を戻していてただの勘違いだった（レビューを通すことで防げたかもしれない）
- #40
    - 環境構築（エディタ整備、CIの導入）が不十分だったため共同作業上のノイズが生じた
    - レビューを通して取り込んだ
    - 共同作業は難しいなと改めて思った
- 以降はアプリのレビューを通してゴソッとタスクが立ってゴソッとタスクが消える（はず）をやっている

### ふりかえり

- 2月19日あたりから着手して大体完成まで30時間くらい（週10時間）
- ソフトウェア開発において「炎上」という表現が使われるけど、今回は「炎上」したのか？~~たぶんしていないほうだと思う~~若干した？判定をおねがいします
- 比較的開発とドキュメンテーションを平行しておこなえていたと思う。ドキュメンテーションは自分以外（未来の自分も自分以外に含める）に**開発参加してもらうとか利用してもらうのには必要**な作業
- 作業メモをとるのは大事（**粒度は細かければ細かいほどいい**けど無理のない範囲で。 GitHub なら issue とかそうでなくてもチケットを切るとか）
- 「この要素がないとこのアプリは作られない」というような部分は**比較的序盤に目星がついて**おり、技術的チャレンジ？は一応その時点で完了した
- 一方で「動く」レベルにもっていくにあたっては、さも「これが正解です」といわんばかりにヒントやスケルトンの提示をしたが、**実際には解は最初から分かっていない**し迷走もした
- 以降はデバッグ、見た目振る舞いの調整などの**作り込みで延々と時間をかけていった**印象

**Comment by dynamis** [comment]
> 大体完成まで30時間くらい

およそ想定通りの時間で収まっている、あるいは危惧したほどは掛からなかった印象です。
(Vue/Nuxt 準備は想定時間を超えていたがこちらは全然越えていない)

綺麗に作って整理しての時間もあるので、実装力のある人が 10-20 時間程度で必要要件を実装出来る、初心者エンジニアとしてはもっと時間をかけて頑張るがある程度作っていける、そのくらいの規模という印象でもあります。

> 今回は「炎上」したのか？

少し残業はしたかも知れないが、炎上はしなかったのだと考えます。

> 作業メモをとるのは大事

こういうところも伝わるような教材になると良いのかも知れません (どうすれば良いのだろう)

> 実際には解は最初から分かっていないし迷走もした

できあがった回答を見せると簡単そうだが実際に作るのはそれよりも遙かに難しい、開発や研究のあるあるですね。紆余曲折する中で学ぶので、学習目的という意味ではそういった試行錯誤が必要なボリューム感で良い感じになったのではと勝手に思ってます。

**Comment by knokmki612** [comment]
説明した
