### ISSUE TITLE
Dialogの配置

### ISSUE THREAD

**Issue by Hidetaro7** [webdino/lyceum-pokemon#60]
https://github.com/webdino/lyceum-pokemon/blob/05abeb7d3c3a171477905cd32ae99ceddf9cbe10/components/GamifyDialog.vue#L58

`position: absolute`だとスクロールしたときに中央に配置されないので`position: fixed`じゃないかなと思いました

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/281424/156737539-e45993a2-1101-4e24-b5e6-9fbb919442ac.png">

**Comment by knokmki612** [comment]
たしかにそうですね、フィードバックありがとうございます
