### ISSUE TITLE
スケルトンの POST /trainer の TODO コメントの曖昧性をなくしたい

### ISSUE THREAD

**Issue by dynamis** [webdino/lyceum-pokemon#95]
https://github.com/webdino/lyceum-pokemon/blob/d9934bc5b7cffac9d2e8eafaccf3d7cc755e4c13/express/index.js#L36-L41
https://github.com/webdino/lyceum-pokemon/blob/87b441e6b47fed7cd39932884e79017dc1d5d469/express/index.js#L36-L41

トレーナー名が何に含まれていなければ 400 なのか、トレーナー名が何に既に存在したら 409 なのか、リクエストボディのデータに含まれてない場合と既存の S3 のトレーナーリストに含まれていない場合で対象が違うのに同じ書きっぷりをしているので実装すべきことを誤解する恐れがある (既存のトレーナーリストの中で名前がないものを検査するようなコードを書き始めている人がいた)。

**Comment by knokmki612** [comment]
#96 にて曖昧性を排除したコメントへの変更をおこない、skeleton-halfwayにもcherry-pickしました。もし引き続き修正の必要ありましたら、直接skeleton-*ブランチを編集いただくか、あらためてissueにしてもらえればと思います
